name: cbl_data
description: >-
  Utilities for data mapping and querying with Couchbase Lite, including
  support for entity and repository pattern.
version: 0.1.0
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cbl: ^0.5.0
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
