name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  formatting-dart:
    name: Formatting - Dart
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Check formatting
        run: melos run formatting:check

  formatting-clang:
    name: Formatting - Clang
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check formatting
        uses: jidicula/clang-format-action@v3.1.0
        with:
          check-path: 'native/cbl-dart/src'

  analyze-dart:
    name: Analyze Dart code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Analyze code
        run: melos run analyze

  build-binaries-linux:
    name: Build - Binaries - Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-binaries-linux

      - name: Build
        run: |
          dpkg -S libc++.so
          dpkg -S libc++abi.so
          ./native/tools/build_linux.sh build
          ./native/tools/build_linux.sh copyToLib
          tar -czf binaries-linux.tar.gz -C build/linux/lib .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries-linux
          path: binaries-linux.tar.gz

  build-binaries-android:
    name: Build - Binaries - Android
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-binaries-android

      - name: Build
        run: |
          ./native/tools/build_android.sh buildAllArchs
          ./native/tools/build_android.sh copyAllArchsToLib
          tar -czf binaries-android.tar.gz -C build/android/lib .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries-android
          path: binaries-android.tar.gz

  build-binaries-apple:
    name: Build - Binaries - Apple
    runs-on: macos-10.15
    environment: Apple
    strategy:
      matrix:
        platform: [ios, ios_simulator, macos]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: build-binaries-apple-${{ matrix.platform }}

      # Doxygen is needed in build of Couchbase-Lite-C, which cannot be easily changed.
      # bash >=4 is needed in build_apple.sh.
      - name: Install dependencies with brew
        run: brew install doxygen bash

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_CERT }}
          p12-password: ${{ secrets.APPLE_DEV_CERT_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_TMP_KEYCHAIN_PASSWORD }}

      - name: Build
        env:
          DEVELOPMENT_TEAM: ${{ secrets.APPLE_DEVELOPMENT_TEAM }}
        run: |
          ./native/tools/build_apple.sh buildPlatform ${{ matrix.platform }}
          tar -czf binaries-apple-${{ matrix.platform }}.tar.gz -C build/apple/archives .

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: binaries-apple-${{ matrix.platform }}
          path: binaries-apple-${{ matrix.platform }}.tar.gz

  build-binaries-apple-xcframeworks:
    name: Build - Binaries - Apple - xcframeworks
    runs-on: macos-10.15
    needs: build-binaries-apple
    env:
      ARCHIVES: build/apple/archives
      XCFRAMEWORKS: build/apple/Xcframeworks
    steps:
      - uses: actions/checkout@v2

      # bash >=4 is needed in build_apple.sh.
      - name: Install dependencies with brew
        run: brew install bash

      - name: Download ios binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-ios

      - name: Download ios_simulator binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-ios_simulator

      - name: Download macos binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-macos

      - name: Unpack archives
        run: |
          mkdir -p "$ARCHIVES"
          tar -xzf binaries-apple-ios.tar.gz -C "$ARCHIVES"
          tar -xzf binaries-apple-ios_simulator.tar.gz -C "$ARCHIVES"
          tar -xzf binaries-apple-macos.tar.gz -C "$ARCHIVES"

      - name: Create xcframeworks
        run: |
          mkdir -p "$XCFRAMEWORKS"
          ./native/tools/build_apple.sh createXcframeworks
          tar -czf binaries-apple-xcframeworks.tar.gz -C "$XCFRAMEWORKS" .

      - name: Upload xcframeworks
        uses: actions/upload-artifact@v2
        with:
          name: binaries-apple-xcframeworks
          path: binaries-apple-xcframeworks.tar.gz

  tests-cbl:
    name: Tests - cbl
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Run tests
        run: melos run test:cbl

  tests-cbl_native:
    name: Tests - cbl_native
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Run tests
        run: melos run test:cbl_native

  tests-standalone-dart-linux:
    name: Tests - Standalone Dart - Linux
    runs-on: ubuntu-20.04
    needs: build-binaries-linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-linux

      - name: Extract binaries
        working-directory: packages/cbl_e2e_tests_standalone_dart
        run: |
          mkdir lib
          tar -xzf ../../binaries-linux.tar.gz -C lib

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Run tests
        run: melos run test:standalone_dart

  tests-standalone-dart-macos:
    name: Tests - Standalone Dart - macOS
    runs-on: macos-10.15
    needs: build-binaries-apple
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-macos

      - name: Extract frameworks from archive
        working-directory: packages/cbl_e2e_tests_standalone_dart
        run: |
          tar -xzf ../../binaries-apple-macos.tar.gz 
          cp -a macos.xcarchive/Products/Library/Frameworks .

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Run tests
        run: melos run test:standalone_dart

  tests-flutter-ios:
    name: Tests - Flutter - iOS
    runs-on: macos-10.15
    needs: build-binaries-apple-xcframeworks
    environment: Apple
    env:
      CBL_FLUTTER_SKIP_INSTALL_BINARIES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_CERT }}
          p12-password: ${{ secrets.APPLE_DEV_CERT_PASSWORD }}
          keychain-password: ${{ secrets.APPLE_TMP_KEYCHAIN_PASSWORD }}

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-xcframeworks

      - name: Extract frameworks from archive
        working-directory: packages/cbl_flutter
        run: |
          mkdir -p Xcframeworks
          tar -xzf ../../binaries-apple-xcframeworks.tar.gz -C Xcframeworks

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Build tests
        run: |
          melos run flutter:prepare
          melos run build:cbl_flutter:test:ios

      - name: Run tests
        working-directory: packages/cbl_flutter/example/ios
        run: fastlane test

  tests-flutter-macos:
    name: Tests - Flutter - macOS
    runs-on: macos-10.15
    needs: build-binaries-apple-xcframeworks
    # Disabled because `flutter drive` ignores `--no-pub` which breaks melos setup
    # Related issue https://github.com/flutter/flutter/issues/76446 
    if: false
    env:
      CBL_FLUTTER_SKIP_INSTALL_BINARIES: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download binaries
        uses: actions/download-artifact@v2
        with:
          name: binaries-apple-xcframeworks

      - name: Extract frameworks from archive
        working-directory: packages/cbl_flutter
        run: |
          mkdir -p Xcframeworks
          tar -xzf ../../binaries-apple-xcframeworks.tar.gz -C Xcframeworks

      - name: Cache Dart dependencies
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            dart-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
            dart-pub-cache

      - name: Setup Dart environment
        uses: ./.github/actions/setup-dart-env

      - name: Enable Flutter on macOS
        run: flutter config --enable-macos-desktop

      - name: Run tests
        working-directory: packages/cbl_flutter/example
        run: |
          flutter drive \
            --no-pub \
            -d macos \
            --driver test_driver/integration_test.dart \
            --target integration_test/cbl_e2e_test.dart
